import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Clean existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.offer.deleteMany();
  await prisma.siteText.deleteMany();
  await prisma.advertisement.deleteMany();
  await prisma.currency.deleteMany();

  // ── Categories ──
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: "Electronics",
        nameAr: "إلكترونيات",
        slug: "electronics",
        icon: "Smartphone",
        description: "أحدث الأجهزة الإلكترونية والهواتف الذكية",
        order: 0,
      },
    }),
    prisma.category.create({
      data: {
        name: "Fashion",
        nameAr: "أزياء",
        slug: "fashion",
        icon: "Shirt",
        description: "أحدث صيحات الموضة والملابس",
        order: 1,
      },
    }),
    prisma.category.create({
      data: {
        name: "Home & Kitchen",
        nameAr: "المنزل والمطبخ",
        slug: "home-kitchen",
        icon: "Home",
        description: "كل ما يحتاجه منزلك من أثاث وأدوات مطبخ",
        order: 2,
      },
    }),
    prisma.category.create({
      data: {
        name: "Beauty & Health",
        nameAr: "الجمال والصحة",
        slug: "beauty-health",
        icon: "Sparkles",
        description: "منتجات العناية بالبشرة والجمال",
        order: 3,
      },
    }),
    prisma.category.create({
      data: {
        name: "Sports",
        nameAr: "رياضة",
        slug: "sports",
        icon: "Dumbbell",
        description: "أدوات ومعدات رياضية متنوعة",
        order: 4,
      },
    }),
    prisma.category.create({
      data: {
        name: "Books",
        nameAr: "كتب",
        slug: "books",
        icon: "BookOpen",
        description: "كتب متنوعة في جميع المجالات",
        order: 5,
      },
    }),
    prisma.category.create({
      data: {
        name: "Toys & Games",
        nameAr: "ألعاب",
        slug: "toys-games",
        icon: "Gamepad2",
        description: "ألعاب للأطفال والكبار",
        order: 6,
      },
    }),
    prisma.category.create({
      data: {
        name: "Automotive",
        nameAr: "سيارات",
        slug: "automotive",
        icon: "Car",
        description: "إكسسوارات وقطع غيار السيارات",
        order: 7,
      },
    }),
    prisma.category.create({
      data: {
        name: "Food & Grocery",
        nameAr: "مواد غذائية",
        slug: "food-grocery",
        icon: "ShoppingBasket",
        description: "مواد غذائية ومشروبات",
        order: 8,
      },
    }),
    prisma.category.create({
      data: {
        name: "Office Supplies",
        nameAr: "مستلزمات مكتبية",
        slug: "office-supplies",
        icon: "Briefcase",
        description: "مستلزمات المكتب والقرطاسية",
        order: 9,
      },
    }),
  ]);

  const [
    catElectronics,
    catFashion,
    catHome,
    catBeauty,
    catSports,
    catBooks,
    catToys,
    catAuto,
    catFood,
    catOffice,
  ] = categories;

  // ── Products ──
  const productsData = [
    // Electronics (5)
    {
      name: "Wireless Bluetooth Headphones",
      nameAr: "سماعات بلوتوث لاسلكية",
      description: "Premium wireless headphones with noise cancellation and 30-hour battery life.",
      descriptionAr: "سماعات لاسلكية فاخرة مع إلغاء الضوضاء وبطارية تدوم 30 ساعة.",
      price: 149.99,
      originalPrice: 199.99,
      image: "/images/products/headphones.png",
      images: JSON.stringify(["/images/products/headphones.png"]),
      brand: "SoundMax",
      brandAr: "ساوند ماكس",
      tags: JSON.stringify(["bluetooth", "wireless", "noise-cancelling"]),
      tagsAr: JSON.stringify(["بلوتوث", "لاسلكي", "إلغاء ضوضاء"]),
      rating: 4.5,
      reviewCount: 128,
      stock: 50,
      featured: true,
      categoryId: catElectronics.id,
    },
    {
      name: "Smart Watch Pro",
      nameAr: "ساعة ذكية برو",
      description: "Advanced smartwatch with health monitoring, GPS, and 7-day battery.",
      descriptionAr: "ساعة ذكية متطورة مع مراقبة صحية وGPS وبطارية 7 أيام.",
      price: 299.99,
      originalPrice: 349.99,
      image: "/images/products/smartwatch.png",
      images: JSON.stringify(["/images/products/smartwatch.png"]),
      brand: "TechFit",
      brandAr: "تك فيت",
      tags: JSON.stringify(["smart", "fitness", "gps"]),
      tagsAr: JSON.stringify(["ذكي", "لياقة", "تتبع"]),
      rating: 4.7,
      reviewCount: 89,
      stock: 35,
      featured: true,
      categoryId: catElectronics.id,
    },
    {
      name: "Portable Bluetooth Speaker",
      nameAr: "مكبر صوت بلوتوث محمول",
      description: "Waterproof portable speaker with 360-degree sound and 12-hour battery.",
      descriptionAr: "مكبر صوت محمول مقاوم للماء بصوت 360 درجة وبطارية 12 ساعة.",
      price: 79.99,
      originalPrice: 99.99,
      image: "/images/products/speaker.png",
      images: JSON.stringify(["/images/products/speaker.png"]),
      brand: "SoundMax",
      brandAr: "ساوند ماكس",
      tags: JSON.stringify(["bluetooth", "portable", "waterproof"]),
      tagsAr: JSON.stringify(["بلوتوث", "محمول", "مقاوم للماء"]),
      rating: 4.3,
      reviewCount: 215,
      stock: 80,
      featured: false,
      categoryId: catElectronics.id,
    },
    {
      name: "USB-C Fast Charger 65W",
      nameAr: "شاحن سريع USB-C 65 واط",
      description: "GaN fast charger compatible with laptops, tablets, and phones.",
      descriptionAr: "شاحن سريع بتقنية GaN متوافق مع اللابتوبات والأجهزة اللوحية والهواتف.",
      price: 34.99,
      originalPrice: 49.99,
      image: "/images/products/charger.png",
      images: JSON.stringify(["/images/products/charger.png"]),
      brand: "PowerVolt",
      brandAr: "باور فولت",
      tags: JSON.stringify(["charger", "usb-c", "fast-charging"]),
      tagsAr: JSON.stringify(["شاحن", "USB-C", "شحن سريع"]),
      rating: 4.6,
      reviewCount: 342,
      stock: 200,
      featured: false,
      categoryId: catElectronics.id,
    },
    {
      name: "Mechanical Gaming Keyboard",
      nameAr: "لوحة مفاتيح ميكانيكية للألعاب",
      description: "RGB mechanical keyboard with Cherry MX switches and aluminum frame.",
      descriptionAr: "لوحة مفاتيح ميكانيكية بإضاءة RGB ومفاتيح Cherry MX وإطار ألمنيوم.",
      price: 119.99,
      originalPrice: 159.99,
      image: "/images/products/keyboard.png",
      images: JSON.stringify(["/images/products/keyboard.png"]),
      brand: "GameZone",
      brandAr: "جيم زون",
      tags: JSON.stringify(["gaming", "mechanical", "rgb"]),
      tagsAr: JSON.stringify(["ألعاب", "ميكانيكي", "إضاءة"]),
      rating: 4.4,
      reviewCount: 67,
      stock: 45,
      featured: false,
      categoryId: catElectronics.id,
    },

    // Fashion (5)
    {
      name: "Premium Cotton T-Shirt",
      nameAr: "تيشيرت قطن فاخر",
      description: "100% Egyptian cotton t-shirt with modern fit and breathable fabric.",
      descriptionAr: "تيشيرت من القطن المصري 100% بقص عصيري وقماش يسمح بالتهوية.",
      price: 29.99,
      originalPrice: 39.99,
      image: "/images/products/tshirt.png",
      images: JSON.stringify(["/images/products/tshirt.png"]),
      brand: "CottonLux",
      brandAr: "كوتون لوكس",
      tags: JSON.stringify(["cotton", "casual", "summer"]),
      tagsAr: JSON.stringify(["قطن", "كاجوال", "صيفي"]),
      rating: 4.2,
      reviewCount: 456,
      stock: 300,
      featured: false,
      categoryId: catFashion.id,
    },
    {
      name: "Leather Belt Classic",
      nameAr: "حزام جلد كلاسيك",
      description: "Genuine leather belt with premium buckle and adjustable size.",
      descriptionAr: "حزام جلد طبيعي مع بكلة فاخرة ومقاس قابل للتعديل.",
      price: 24.99,
      originalPrice: 34.99,
      image: "/images/products/belt.png",
      images: JSON.stringify(["/images/products/belt.png"]),
      brand: "LeatherCraft",
      brandAr: "ليذر كرافت",
      tags: JSON.stringify(["leather", "classic", "accessories"]),
      tagsAr: JSON.stringify(["جلد", "كلاسيك", "إكسسوارات"]),
      rating: 4.1,
      reviewCount: 189,
      stock: 150,
      featured: false,
      categoryId: catFashion.id,
    },
    {
      name: "Running Shoes Air Max",
      nameAr: "حذاء رياضي اير ماكس",
      description: "Lightweight running shoes with air cushioning and breathable mesh.",
      descriptionAr: "حذاء رياضي خفيف مع وسادة هوائية وشبك يسمح بالتهوية.",
      price: 89.99,
      originalPrice: 129.99,
      image: "/images/products/shoes.png",
      images: JSON.stringify(["/images/products/shoes.png"]),
      brand: "SportFlex",
      brandAr: "سبورت فليكس",
      tags: JSON.stringify(["running", "shoes", "sportswear"]),
      tagsAr: JSON.stringify(["جري", "أحذية", "ملابس رياضية"]),
      rating: 4.6,
      reviewCount: 312,
      stock: 75,
      featured: true,
      categoryId: catFashion.id,
    },
    {
      name: "Silk Scarf Elegant",
      nameAr: "وشاح حرير أنيق",
      description: "Handcrafted silk scarf with beautiful patterns, perfect for any occasion.",
      descriptionAr: "وشاح حرير مصنوع يدوياً بنقوش جميلة، مثالي لكل المناسبات.",
      price: 49.99,
      originalPrice: 69.99,
      image: "/images/products/scarf.png",
      images: JSON.stringify(["/images/products/scarf.png"]),
      brand: "SilkRoad",
      brandAr: "سيلك رود",
      tags: JSON.stringify(["silk", "elegant", "accessories"]),
      tagsAr: JSON.stringify(["حرير", "أنيق", "إكسسوارات"]),
      rating: 4.3,
      reviewCount: 98,
      stock: 60,
      featured: false,
      categoryId: catFashion.id,
    },
    {
      name: "Denim Jacket Modern",
      nameAr: "جاكيت جينز عصري",
      description: "Modern denim jacket with vintage wash and comfortable stretch fabric.",
      descriptionAr: "جاكيت جينز عصري بغسيل كلاسيكي وقماش مطاطي مريح.",
      price: 69.99,
      originalPrice: 89.99,
      image: "/images/products/denim.png",
      images: JSON.stringify(["/images/products/denim.png"]),
      brand: "UrbanWear",
      brandAr: "أوربان وير",
      tags: JSON.stringify(["denim", "jacket", "casual"]),
      tagsAr: JSON.stringify(["جينز", "جاكيت", "كاجوال"]),
      rating: 4.4,
      reviewCount: 156,
      stock: 40,
      featured: false,
      categoryId: catFashion.id,
    },

    // Home & Kitchen (5)
    {
      name: "Stainless Steel Cookware Set",
      nameAr: "طقم أواني طبخ ستانلس ستيل",
      description: "10-piece professional stainless steel cookware set with copper core.",
      descriptionAr: "طقم 10 قطع من أواني الطبخ الاحترافية من الستانلس ستيل مع نواة نحاسية.",
      price: 199.99,
      originalPrice: 279.99,
      image: "/images/products/cookware.png",
      images: JSON.stringify(["/images/products/cookware.png"]),
      brand: "ChefPro",
      brandAr: "شيف برو",
      tags: JSON.stringify(["cookware", "kitchen", "stainless-steel"]),
      tagsAr: JSON.stringify(["أواني طبخ", "مطبخ", "ستانلس ستيل"]),
      rating: 4.8,
      reviewCount: 234,
      stock: 25,
      featured: true,
      categoryId: catHome.id,
    },
    {
      name: "Smart LED Lamp",
      nameAr: "مصباح LED ذكي",
      description: "WiFi-enabled smart lamp with 16 million colors and voice control.",
      descriptionAr: "مصباح ذكي يعمل بالواي فاي مع 16 مليون لون وتحكم صوتي.",
      price: 44.99,
      originalPrice: 59.99,
      image: "/images/products/lamp.png",
      images: JSON.stringify(["/images/products/lamp.png"]),
      brand: "BrightHome",
      brandAr: "برايت هوم",
      tags: JSON.stringify(["smart", "led", "wifi"]),
      tagsAr: JSON.stringify(["ذكي", "LED", "واي فاي"]),
      rating: 4.2,
      reviewCount: 167,
      stock: 120,
      featured: false,
      categoryId: catHome.id,
    },
    {
      name: "Bamboo Cutting Board Set",
      nameAr: "طقم ألواح تقطيع بامبو",
      description: "Set of 3 organic bamboo cutting boards in different sizes.",
      descriptionAr: "طقم 3 ألواح تقطيع من البامبو العضوي بمقاسات مختلفة.",
      price: 27.99,
      originalPrice: 39.99,
      image: "/images/products/cuttingboard.png",
      images: JSON.stringify(["/images/products/cuttingboard.png"]),
      brand: "EcoKitchen",
      brandAr: "إيكو كيتشن",
      tags: JSON.stringify(["bamboo", "kitchen", "eco-friendly"]),
      tagsAr: JSON.stringify(["بامبو", "مطبخ", "صديق للبيئة"]),
      rating: 4.5,
      reviewCount: 203,
      stock: 90,
      featured: false,
      categoryId: catHome.id,
    },
    {
      name: "Air Purifier HEPA",
      nameAr: "جهاز تنقية الهواء HEPA",
      description: "True HEPA air purifier covering 500 sq ft with auto mode.",
      descriptionAr: "جهاز تنقية هواء بفلتر HEPA حقيقي يغطي 500 قدم مربع مع وضع تلقائي.",
      price: 129.99,
      originalPrice: 179.99,
      image: "/images/products/purifier.png",
      images: JSON.stringify(["/images/products/purifier.png"]),
      brand: "PureAir",
      brandAr: "بيور إير",
      tags: JSON.stringify(["air-purifier", "hepa", "home"]),
      tagsAr: JSON.stringify(["تنقية هواء", "HEPA", "منزل"]),
      rating: 4.6,
      reviewCount: 89,
      stock: 55,
      featured: false,
      categoryId: catHome.id,
    },
    {
      name: "Electric Kettle 1.7L",
      nameAr: "غلاية كهربائية 1.7 لتر",
      description: "Fast-boiling electric kettle with temperature control and keep-warm function.",
      descriptionAr: "غلاية كهربائية سريعة الغلي مع تحكم بدرجة الحرارة ووظيفة الإبقاء دافئاً.",
      price: 39.99,
      originalPrice: 54.99,
      image: "/images/products/kettle.png",
      images: JSON.stringify(["/images/products/kettle.png"]),
      brand: "BrewMaster",
      brandAr: "برو ماستر",
      tags: JSON.stringify(["kettle", "kitchen", "electric"]),
      tagsAr: JSON.stringify(["غلاية", "مطبخ", "كهربائي"]),
      rating: 4.3,
      reviewCount: 278,
      stock: 110,
      featured: false,
      categoryId: catHome.id,
    },

    // Beauty & Health (4)
    {
      name: "Vitamin C Serum",
      nameAr: "سيروم فيتامين سي",
      description: "Professional grade vitamin C serum with hyaluronic acid for brighter skin.",
      descriptionAr: "سيروم فيتامين سي احترافي مع حمض الهيالورونيك لبشرة أكثر إشراقاً.",
      price: 34.99,
      originalPrice: 49.99,
      image: "/images/products/serum.png",
      images: JSON.stringify(["/images/products/serum.png"]),
      brand: "GlowSkin",
      brandAr: "جلو سكين",
      tags: JSON.stringify(["skincare", "vitamin-c", "serum"]),
      tagsAr: JSON.stringify(["عناية بالبشرة", "فيتامين سي", "سيروم"]),
      rating: 4.7,
      reviewCount: 523,
      stock: 200,
      featured: true,
      categoryId: catBeauty.id,
    },
    {
      name: "Hair Care Oil Argan",
      nameAr: "زيت أرغان للعناية بالشعر",
      description: "Pure Moroccan argan oil for hair nourishment and shine.",
      descriptionAr: "زيت أرغان مغربي نقي لتغذية الشعر ومنحه لمعاناً.",
      price: 19.99,
      originalPrice: 29.99,
      image: "/images/products/arganoil.png",
      images: JSON.stringify(["/images/products/arganoil.png"]),
      brand: "NaturalGlow",
      brandAr: "ناتشورال جلو",
      tags: JSON.stringify(["hair-care", "argan", "natural"]),
      tagsAr: JSON.stringify(["عناية بالشعر", "أرغان", "طبيعي"]),
      rating: 4.4,
      reviewCount: 312,
      stock: 180,
      featured: false,
      categoryId: catBeauty.id,
    },
    {
      name: "Sunscreen SPF 50+",
      nameAr: "واقي شمس SPF 50+",
      description: "Lightweight sunscreen with SPF 50+ protection, non-greasy formula.",
      descriptionAr: "واقي شمس خفيف بحماية SPF 50+، تركيبة غير دهنية.",
      price: 14.99,
      originalPrice: 22.99,
      image: "/images/products/sunscreen.png",
      images: JSON.stringify(["/images/products/sunscreen.png"]),
      brand: "SunShield",
      brandAr: "سان شيلد",
      tags: JSON.stringify(["sunscreen", "spf", "skincare"]),
      tagsAr: JSON.stringify(["واقي شمس", "SPF", "عناية بالبشرة"]),
      rating: 4.5,
      reviewCount: 445,
      stock: 300,
      featured: false,
      categoryId: catBeauty.id,
    },
    {
      name: "Electric Toothbrush Sonic",
      nameAr: "فرشاة أسنان كهربائية سونيك",
      description: "Sonic electric toothbrush with 5 modes and 2-minute smart timer.",
      descriptionAr: "فرشاة أسنان كهربائية سونيك مع 5 أوضاع ومؤقت ذكي دقيقتين.",
      price: 59.99,
      originalPrice: 79.99,
      image: "/images/products/toothbrush.png",
      images: JSON.stringify(["/images/products/toothbrush.png"]),
      brand: "DentaCare",
      brandAr: "دينتا كير",
      tags: JSON.stringify(["oral-care", "electric", "sonic"]),
      tagsAr: JSON.stringify(["عناية فموية", "كهربائي", "سونيك"]),
      rating: 4.6,
      reviewCount: 187,
      stock: 95,
      featured: false,
      categoryId: catBeauty.id,
    },

    // Sports (3)
    {
      name: "Yoga Mat Premium 6mm",
      nameAr: "سجادة يوغا فاخرة 6 مم",
      description: "Non-slip premium yoga mat with alignment lines and carrying strap.",
      descriptionAr: "سجادة يوغا فاخرة مانعة للانزلاق مع خطوط توجيهية وحملة.",
      price: 34.99,
      originalPrice: 49.99,
      image: "/images/products/yogamat.png",
      images: JSON.stringify(["/images/products/yogamat.png"]),
      brand: "ZenFit",
      brandAr: "زن فيت",
      tags: JSON.stringify(["yoga", "fitness", "mat"]),
      tagsAr: JSON.stringify(["يوغا", "لياقة", "سجادة"]),
      rating: 4.5,
      reviewCount: 234,
      stock: 130,
      featured: false,
      categoryId: catSports.id,
    },
    {
      name: "Adjustable Dumbbell Set",
      nameAr: "طقم دامبلز قابل للتعديل",
      description: "Adjustable dumbbell set from 5-52.5 lbs with quick-change mechanism.",
      descriptionAr: "طقم دامبلز قابل للتعديل من 5 إلى 52.5 رطل مع آلية تبديل سريعة.",
      price: 249.99,
      originalPrice: 349.99,
      image: "/images/products/dumbbell.png",
      images: JSON.stringify(["/images/products/dumbbell.png"]),
      brand: "IronFlex",
      brandAr: "آيرون فليكس",
      tags: JSON.stringify(["dumbbell", "weights", "strength"]),
      tagsAr: JSON.stringify(["دامبلز", "أوزان", "قوة"]),
      rating: 4.8,
      reviewCount: 156,
      stock: 20,
      featured: true,
      categoryId: catSports.id,
    },
    {
      name: "Insulated Water Bottle 32oz",
      nameAr: "زجاجة ماء معزولة 32 أونصة",
      description: "Double-wall vacuum insulated water bottle, keeps cold 24h / hot 12h.",
      descriptionAr: "زجاجة ماء معزولة بالتفريغ المزدوج، تحفظ البرد 24 ساعة والسخون 12 ساعة.",
      price: 24.99,
      originalPrice: 34.99,
      image: "/images/products/waterbottle.png",
      images: JSON.stringify(["/images/products/waterbottle.png"]),
      brand: "HydroElite",
      brandAr: "هايدرو إيليت",
      tags: JSON.stringify(["water-bottle", "insulated", "sport"]),
      tagsAr: JSON.stringify(["زجاجة ماء", "معزولة", "رياضة"]),
      rating: 4.4,
      reviewCount: 389,
      stock: 250,
      featured: false,
      categoryId: catSports.id,
    },

    // Books (2)
    {
      name: "Arabic Calligraphy Guide",
      nameAr: "دليل الخط العربي",
      description: "Comprehensive guide to Arabic calligraphy with step-by-step instructions.",
      descriptionAr: "دليل شامل للخط العربي مع تعليمات خطوة بخطوة.",
      price: 22.99,
      originalPrice: 29.99,
      image: "/images/products/calligraphy.png",
      images: JSON.stringify(["/images/products/calligraphy.png"]),
      brand: "عالم الكتب",
      brandAr: "عالم الكتب",
      tags: JSON.stringify(["arabic", "calligraphy", "art"]),
      tagsAr: JSON.stringify(["عربي", "خط", "فن"]),
      rating: 4.3,
      reviewCount: 78,
      stock: 60,
      featured: false,
      categoryId: catBooks.id,
    },
    {
      name: "Business Strategy Handbook",
      nameAr: "دليل استراتيجيات الأعمال",
      description: "Modern business strategy handbook with case studies and frameworks.",
      descriptionAr: "دليل استراتيجيات الأعمال الحديثة مع دراسات حالة وأطر عمل.",
      price: 18.99,
      originalPrice: 24.99,
      image: "/images/products/business.png",
      images: JSON.stringify(["/images/products/business.png"]),
      brand: "BusinessPress",
      brandAr: "برس بزنس",
      tags: JSON.stringify(["business", "strategy", "management"]),
      tagsAr: JSON.stringify(["أعمال", "استراتيجية", "إدارة"]),
      rating: 4.1,
      reviewCount: 145,
      stock: 85,
      featured: false,
      categoryId: catBooks.id,
    },

    // Toys & Games (2)
    {
      name: "Building Blocks Set 500pcs",
      nameAr: "طقم مكعبات بناء 500 قطعة",
      description: "Creative building blocks set with 500 pieces in various colors and shapes.",
      descriptionAr: "طقم مكعبات بناء إبداعي بـ 500 قطعة بألوان وأشكال متنوعة.",
      price: 39.99,
      originalPrice: 54.99,
      image: "/images/products/blocks.png",
      images: JSON.stringify(["/images/products/blocks.png"]),
      brand: "FunBuild",
      brandAr: "فان بيلد",
      tags: JSON.stringify(["building", "kids", "creative"]),
      tagsAr: JSON.stringify(["بناء", "أطفال", "إبداعي"]),
      rating: 4.6,
      reviewCount: 267,
      stock: 70,
      featured: false,
      categoryId: catToys.id,
    },
    {
      name: "Board Game Family Edition",
      nameAr: "لعبة لوحة نسخة العائلة",
      description: "Fun family board game for 2-6 players, ages 8 and up.",
      descriptionAr: "لعبة لوحة عائلية ممتعة لـ 2-6 لاعبين، من عمر 8 سنوات فما فوق.",
      price: 29.99,
      originalPrice: 39.99,
      image: "/images/products/boardgame.png",
      images: JSON.stringify(["/images/products/boardgame.png"]),
      brand: "GameNite",
      brandAr: "جيم نايت",
      tags: JSON.stringify(["board-game", "family", "fun"]),
      tagsAr: JSON.stringify(["لعبة لوحة", "عائلة", "متعة"]),
      rating: 4.5,
      reviewCount: 134,
      stock: 55,
      featured: false,
      categoryId: catToys.id,
    },

    // Automotive (3)
    {
      name: "Car Phone Mount Magnetic",
      nameAr: "حامل هاتف سيارة مغناطيسي",
      description: "Universal magnetic car phone mount with 360° rotation and strong grip.",
      descriptionAr: "حامل هاتف سيارة مغناطيسي عالمي مع دوران 360 درجة وقبضة قوية.",
      price: 14.99,
      originalPrice: 24.99,
      image: "/images/products/phonemount.png",
      images: JSON.stringify(["/images/products/phonemount.png"]),
      brand: "DriveSafe",
      brandAr: "درايف سيف",
      tags: JSON.stringify(["car", "phone-mount", "magnetic"]),
      tagsAr: JSON.stringify(["سيارة", "حامل هاتف", "مغناطيسي"]),
      rating: 4.2,
      reviewCount: 456,
      stock: 300,
      featured: false,
      categoryId: catAuto.id,
    },
    {
      name: "Dashboard Camera 4K",
      nameAr: "كاميرا لوحة القيادة 4K",
      description: "4K dash cam with night vision, GPS, and 170° wide angle lens.",
      descriptionAr: "كاميرا لوحة قيادة 4K مع رؤية ليلية وGPS وعدسة واسعة 170 درجة.",
      price: 89.99,
      originalPrice: 129.99,
      image: "/images/products/dashcam.png",
      images: JSON.stringify(["/images/products/dashcam.png"]),
      brand: "RoadEye",
      brandAr: "رود آي",
      tags: JSON.stringify(["dashcam", "4k", "car-safety"]),
      tagsAr: JSON.stringify(["كاميرا سيارة", "4K", "سلامة"]),
      rating: 4.5,
      reviewCount: 198,
      stock: 65,
      featured: false,
      categoryId: catAuto.id,
    },
    {
      name: "Car Vacuum Cleaner Portable",
      nameAr: "مكنسة سيارة محمولة",
      description: "Powerful portable car vacuum with multiple attachments and HEPA filter.",
      descriptionAr: "مكنسة سيارة محمولة قوية مع ملحقات متعددة وفلتر HEPA.",
      price: 34.99,
      originalPrice: 49.99,
      image: "/images/products/carvacuum.png",
      images: JSON.stringify(["/images/products/carvacuum.png"]),
      brand: "CleanDrive",
      brandAr: "كلين درايف",
      tags: JSON.stringify(["vacuum", "car-care", "portable"]),
      tagsAr: JSON.stringify(["مكنسة", "عناية سيارة", "محمول"]),
      rating: 4.1,
      reviewCount: 223,
      stock: 100,
      featured: false,
      categoryId: catAuto.id,
    },

    // Food & Grocery (3)
    {
      name: "Premium Arabic Coffee 500g",
      nameAr: "قهوة عربية فاخرة 500 جرام",
      description: "Traditional Arabic coffee blended with cardamom, premium quality beans.",
      descriptionAr: "قهوة عربية تقليدية ممزوجة بالهيل، حبوب بجودة فاخرة.",
      price: 24.99,
      originalPrice: 32.99,
      image: "/images/products/arabcoffee.png",
      images: JSON.stringify(["/images/products/arabcoffee.png"]),
      brand: "قهوة الأصيل",
      brandAr: "قهوة الأصيل",
      tags: JSON.stringify(["coffee", "arabic", "premium"]),
      tagsAr: JSON.stringify(["قهوة", "عربية", "فاخرة"]),
      rating: 4.8,
      reviewCount: 567,
      stock: 200,
      featured: true,
      categoryId: catFood.id,
    },
    {
      name: "Organic Dates Box 1kg",
      nameAr: "علبة تمر عضوي 1 كجم",
      description: "Premium Medjool dates, organic and naturally sweet, 1kg box.",
      descriptionAr: "تمر مجدول فاخر، عضوي وحلو طبيعياً، علبة 1 كجم.",
      price: 29.99,
      originalPrice: 39.99,
      image: "/images/products/dates.png",
      images: JSON.stringify(["/images/products/dates.png"]),
      brand: "واحة التمر",
      brandAr: "واحة التمر",
      tags: JSON.stringify(["dates", "organic", "snack"]),
      tagsAr: JSON.stringify(["تمر", "عضوي", "وجبة خفيفة"]),
      rating: 4.9,
      reviewCount: 389,
      stock: 150,
      featured: false,
      categoryId: catFood.id,
    },
    {
      name: "Mixed Nuts Gift Box",
      nameAr: "صندوق مكسرات هدية",
      description: "Premium mixed nuts gift box with almonds, cashews, pistachios, and walnuts.",
      descriptionAr: "صندوق مكسرات فاخرة للهدية مع لوز وكاجو وفستق وجوز.",
      price: 44.99,
      originalPrice: 59.99,
      image: "/images/products/nuts.png",
      images: JSON.stringify(["/images/products/nuts.png"]),
      brand: "مكسرات الشرق",
      brandAr: "مكسرات الشرق",
      tags: JSON.stringify(["nuts", "gift", "premium"]),
      tagsAr: JSON.stringify(["مكسرات", "هدية", "فاخر"]),
      rating: 4.7,
      reviewCount: 234,
      stock: 80,
      featured: false,
      categoryId: catFood.id,
    },

    // Office Supplies (3)
    {
      name: "Ergonomic Office Chair",
      nameAr: "كرسي مكتب مريح",
      description: "Ergonomic office chair with lumbar support, adjustable height, and breathable mesh.",
      descriptionAr: "كرسي مكتب مريح مع دعم قطني وارتفاع قابل للتعديل وشبك يسمح بالتهوية.",
      price: 249.99,
      originalPrice: 349.99,
      image: "/images/products/officechair.png",
      images: JSON.stringify(["/images/products/officechair.png"]),
      brand: "ComfortDesk",
      brandAr: "كومفورت ديسك",
      tags: JSON.stringify(["office", "ergonomic", "chair"]),
      tagsAr: JSON.stringify(["مكتب", "مريح", "كرسي"]),
      rating: 4.6,
      reviewCount: 178,
      stock: 30,
      featured: true,
      categoryId: catOffice.id,
    },
    {
      name: "Wireless Mouse Silent",
      nameAr: "ماوس لاسلكي صامت",
      description: "Silent wireless mouse with ergonomic design and long battery life.",
      descriptionAr: "ماوس لاسلكي صامت بتصميم مريح وبطارية طويلة العمر.",
      price: 19.99,
      originalPrice: 29.99,
      image: "/images/products/mouse.png",
      images: JSON.stringify(["/images/products/mouse.png"]),
      brand: "ClickPro",
      brandAr: "كليك برو",
      tags: JSON.stringify(["mouse", "wireless", "silent"]),
      tagsAr: JSON.stringify(["ماوس", "لاسلكي", "صامت"]),
      rating: 4.3,
      reviewCount: 234,
      stock: 250,
      featured: false,
      categoryId: catOffice.id,
    },
    {
      name: "Notebook Set Premium A5",
      nameAr: "طقم دفاتر فاخرة A5",
      description: "Set of 3 premium A5 notebooks with thick paper and elegant covers.",
      descriptionAr: "طقم 3 دفاتر فاخرة مقاس A5 بورق سميك وأغلفة أنيقة.",
      price: 16.99,
      originalPrice: 24.99,
      image: "/images/products/notebook.png",
      images: JSON.stringify(["/images/products/notebook.png"]),
      brand: "PaperCraft",
      brandAr: "بيبر كرافت",
      tags: JSON.stringify(["notebook", "stationery", "office"]),
      tagsAr: JSON.stringify(["دفتر", "قرطاسية", "مكتب"]),
      rating: 4.2,
      reviewCount: 167,
      stock: 180,
      featured: false,
      categoryId: catOffice.id,
    },
  ];

  const products = [];
  for (const pData of productsData) {
    products.push(await prisma.product.create({ data: pData }));
  }

  // ── Offers ──
  await Promise.all([
    prisma.offer.create({
      data: {
        title: "Mega Electronics Sale",
        titleAr: "تخفيضات الإلكترونيات الضخمة",
        description: "Up to 30% off on all electronics this week!",
        descriptionAr: "خصم يصل إلى 30% على جميع الإلكترونيات هذا الأسبوع!",
        discountPercent: 30,
        badge: "HOT",
        badgeAr: "ساخن",
        gradient: "from-red-500 to-orange-600",
        ctaText: "Shop Electronics",
        ctaTextAr: "تسوق الإلكترونيات",
        link: "/products?category=electronics",
        active: true,
        order: 0,
      },
    }),
    prisma.offer.create({
      data: {
        title: "Fashion Week Special",
        titleAr: "عروض أسبوع الموضة",
        description: "New arrivals with exclusive discounts up to 40%!",
        descriptionAr: "وصولات جديدة بخصومات حصرية تصل إلى 40%!",
        discountPercent: 40,
        badge: "NEW",
        badgeAr: "جديد",
        gradient: "from-purple-500 to-pink-600",
        ctaText: "Explore Fashion",
        ctaTextAr: "استكشف الموضة",
        link: "/products?category=fashion",
        active: true,
        order: 1,
      },
    }),
    prisma.offer.create({
      data: {
        title: "Home Makeover Deals",
        titleAr: "عروض تجديد المنزل",
        description: "Transform your home with savings up to 25% on home essentials!",
        descriptionAr: "حوّل منزلك بتوفير يصل إلى 25% على مستلزمات المنزل!",
        discountPercent: 25,
        badge: "DEAL",
        badgeAr: "صفقة",
        gradient: "from-emerald-500 to-teal-600",
        ctaText: "Shop Home",
        ctaTextAr: "تسوق المنزل",
        link: "/products?category=home-kitchen",
        active: true,
        order: 2,
      },
    }),
    prisma.offer.create({
      data: {
        title: "Beauty Flash Sale",
        titleAr: "تخفيضات الجمال السريعة",
        description: "Limited time beauty deals with discounts up to 35%!",
        descriptionAr: "عروض جمال لفترة محدودة بخصومات تصل إلى 35%!",
        discountPercent: 35,
        badge: "SALE",
        badgeAr: "تخفيض",
        gradient: "from-pink-500 to-rose-600",
        ctaText: "Shop Beauty",
        ctaTextAr: "تسوق الجمال",
        link: "/products?category=beauty-health",
        active: true,
        order: 3,
      },
    }),
  ]);

  // ── Site Texts ──
  await Promise.all([
    prisma.siteText.create({
      data: {
        key: "announcement_1",
        value: "Free shipping on orders over $50!",
        valueAr: "شحن مجاني للطلبات فوق 50 دولار!",
        group: "announcement",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "announcement_2",
        value: "New arrivals every week — Stay tuned!",
        valueAr: "وصولات جديدة كل أسبوع — تابعونا!",
        group: "announcement",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "announcement_3",
        value: "Easy returns within 30 days",
        valueAr: "إرجاع سهل خلال 30 يوم",
        group: "announcement",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "site_name",
        value: "Z Shop",
        valueAr: "متجر Z",
        group: "general",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "site_tagline",
        value: "Your One-Stop Online Store",
        valueAr: "متجرك الإلكتروني الشامل",
        group: "general",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "site_description",
        value: "Discover the best products at amazing prices",
        valueAr: "اكتشف أفضل المنتجات بأسعار مذهلة",
        group: "general",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "hero_title",
        value: "Discover Amazing Products",
        valueAr: "اكتشف منتجات مذهلة",
        group: "hero",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "hero_subtitle",
        value: "Shop the latest trends with exclusive deals",
        valueAr: "تسوق أحدث الصيحات مع عروض حصرية",
        group: "hero",
      },
    }),
    prisma.siteText.create({
      data: {
        key: "hero_cta",
        value: "Start Shopping",
        valueAr: "ابدأ التسوق",
        group: "hero",
      },
    }),
  ]);

  // ── Advertisements ──
  await Promise.all([
    prisma.advertisement.create({
      data: {
        title: "Summer Collection 2025",
        titleAr: "مجموعة صيف 2025",
        description: "Check out our latest summer fashion collection",
        descriptionAr: "ت découvح أحدث مجموعة أزياء الصيف",
        image: "/images/ads/summer-collection.png",
        link: "/products?category=fashion",
        position: "banner",
        active: true,
        order: 0,
      },
    }),
    prisma.advertisement.create({
      data: {
        title: "Tech Deals Week",
        titleAr: "أسبوع عروض التقنية",
        description: "Unbeatable prices on the latest gadgets",
        descriptionAr: "أسعار لا تقاوم على أحدث الأجهزة",
        image: "/images/ads/tech-deals.png",
        link: "/products?category=electronics",
        position: "sidebar",
        active: true,
        order: 1,
      },
    }),
    prisma.advertisement.create({
      data: {
        title: "Ramadan Special Offers",
        titleAr: "عروض رمضان الخاصة",
        description: "Special deals for the holy month",
        descriptionAr: "عروض خاصة للشهر الكريم",
        image: "/images/ads/ramadan-offers.png",
        link: "/products",
        position: "banner",
        active: true,
        order: 2,
      },
    }),
  ]);

  // ── Currencies ──
  const currenciesData = [
    { code: 'USD', name: 'US Dollar', nameAr: 'دولار أمريكي', symbol: '$', exchangeRate: 1, isDefault: true, active: true, order: 0 },
    { code: 'SAR', name: 'Saudi Riyal', nameAr: 'ريال سعودي', symbol: 'ر.س', exchangeRate: 3.75, isDefault: false, active: true, order: 1 },
    { code: 'AED', name: 'UAE Dirham', nameAr: 'درهم إماراتي', symbol: 'د.إ', exchangeRate: 3.67, isDefault: false, active: true, order: 2 },
    { code: 'EUR', name: 'Euro', nameAr: 'يورو', symbol: '€', exchangeRate: 0.92, isDefault: false, active: true, order: 3 },
    { code: 'GBP', name: 'British Pound', nameAr: 'جنيه إسترليني', symbol: '£', exchangeRate: 0.79, isDefault: false, active: true, order: 4 },
    { code: 'KWD', name: 'Kuwaiti Dinar', nameAr: 'دينار كويتي', symbol: 'د.ك', exchangeRate: 0.31, isDefault: false, active: true, order: 5 },
    { code: 'QAR', name: 'Qatari Riyal', nameAr: 'ريال قطري', symbol: 'ر.ق', exchangeRate: 3.64, isDefault: false, active: true, order: 6 },
    { code: 'BHD', name: 'Bahraini Dinar', nameAr: 'دينار بحريني', symbol: 'د.ب', exchangeRate: 0.38, isDefault: false, active: true, order: 7 },
    { code: 'OMR', name: 'Omani Rial', nameAr: 'ريال عماني', symbol: 'ر.ع', exchangeRate: 0.38, isDefault: false, active: true, order: 8 },
    { code: 'EGP', name: 'Egyptian Pound', nameAr: 'جنيه مصري', symbol: 'ج.م', exchangeRate: 48.5, isDefault: false, active: true, order: 9 },
    { code: 'JOD', name: 'Jordanian Dinar', nameAr: 'دينار أردني', symbol: 'د.أ', exchangeRate: 0.71, isDefault: false, active: true, order: 10 },
    { code: 'IQD', name: 'Iraqi Dinar', nameAr: 'دينار عراقي', symbol: 'د.ع', exchangeRate: 1310, isDefault: false, active: true, order: 11 },
    { code: 'YER', name: 'Yemeni Rial', nameAr: 'ريال يمني', symbol: 'ر.ي', exchangeRate: 530, isDefault: false, active: true, order: 12 },
  ]

  for (const cData of currenciesData) {
    await prisma.currency.create({ data: cData })
  }

  console.log("✅ Seeding complete!");
  console.log(`   - ${categories.length} categories`);
  console.log(`   - ${products.length} products`);
  console.log(`   - 4 offers`);
  console.log(`   - 9 site texts`);
  console.log(`   - 3 advertisements`);
  console.log(`   - ${currenciesData.length} currencies`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
